M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu22.04.1} date 2026-03-23T14:42:36-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-23T14:42:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1200
%
G90
G05
T1
X4.143Y-2.4211
X4.528Y-2.4242
X5.614Y-2.4092
M30
